# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "hugo-module-img-srcset"
license = "The Unlicense"
licenselink = "https://github.com/jan-xyz/hugo-module-img-srcset/blob/master/LICENSE.md"
description = "A Hugo module to modify image Markdown tags to support srcsets"
homepage = "https://github.com/jan-xyz/hugo-module-img-srcset"
tags = ["layout", "image", "responsive"]
features = ["layout"]
min_version = "0.73.0"

[author]
  name = "jan-xyz"
  homepage = "https://jan-steinke.de/"
